services:
    mock-service:
      build:
        context: ..
        dockerfile: deployment/Dockerfile
      ports:
        - '7641:7641'
      environment:
          - APP_VERSION=${APP_VERSION:-v1}
      command: [ 'uvicorn', 'app.main:app', '--host', '0.0.0.0', '--port', '7641' ]
